features:
  - name: "localization_mocap"
    group: "定位模块"
    description: "无人机定位模块：基于MOCAP定位"
    auto_start: false
    stop_timeout_sec: 8.0
    launches:
      - name: "localization"
        package: "localization_fusion"
        file: "localization_fusion.launch"
        args:
          - "source_id:=1"
          - "agent_name:=uav"
          - "agent_id:=1"
          - "enable_monitor:=true"
        delay_sec: 1.0
  - name: "localization_vins"
    group: "定位模块"
    description: "无人机定位模块：基于VINS定位"
    auto_start: false
    stop_timeout_sec: 8.0
    launches:
      - name: "localization"
        package: "localization_fusion"
        file: "localization_fusion.launch"
        args:
          - "source_id:=2"
          - "agent_name:=uav"
          - "agent_id:=1"
          - "enable_monitor:=true"
        delay_sec: 1.0
  - name: "localization_fastlio"
    group: "定位模块"
    description: "无人机定位模块：基于Fast_LIO_EKF定位"
    auto_start: false
    stop_timeout_sec: 8.0
    launches:
      - name: "localization"
        package: "localization_fusion"
        file: "localization_fusion.launch"
        args:
          - "source_id:=6"
          - "agent_name:=uav"
          - "agent_id:=1"
          - "enable_monitor:=true"
        delay_sec: 1.0

  - name: "uav_control_px4_origin"
    group: "控制模块"
    description: "无人机控制模块：基于PX4原生控制器"
    auto_start: false
    depends_on:
      - "localization_mocap"
    stop_timeout_sec: 8.0
    launches:
      - name: "control"
        package: "sunray_uav_control"
        file: "uav_control.launch"
        args:
          - "agent_name:=uav"
          - "agent_id:=1"
          - "enable_single_monitor:=true"
          - "basic_param/controller_types:=0"
        delay_sec: 1.0

  - name: "uav_control_attitude_controller"
    group: "控制模块"
    description: "无人机控制模块：基于attitude_controller"
    auto_start: false
    depends_on:
      - "localization_mocap"
    stop_timeout_sec: 8.0
    launches:
      - name: "control"
        package: "sunray_uav_control"
        file: "uav_control.launch"
        args:
          - "agent_name:=uav"
          - "agent_id:=1"
          - "enable_single_monitor:=true"
          - "basic_param/controller_types:=1"