<?xml version="1.0"?>
<package format="2">
  <name>sunray_planning</name>
  <version>0.0.0</version>
  <description>The sunray_planning package.</description>

  <maintainer email="taolin@todo.todo">taolin</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>
  <depend>sunray_planner_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>roscpp</depend>
  <depend>roslib</depend>
  <depend>sunray_common</depend>
  <depend>sunray_msgs</depend>

  <export/>
</package>
