# vision_pose_config.yaml设计的意图是，根据localization模块传出的外部定位源external_source参数，配置和检查对应的px4参数，订阅里程计并向px4进行融合
# 注意：请确保此处定位源对应的source_id与localizatoin_source.yaml 一一对应
# 使用config.yaml同步px4参数，并不代表px4_paramManager就没有作用了，他仍旧在其他的模块中做贡献

sources_list:                                
  # 定位源的名称，主要是语义化，并不表示我们通过字符串进行查找定位源参数，主要使用source_id进行查找
  VIOBOT:
    # sources_id 表示该定位源的id序号，订阅OdomStatus进行查找
    source_id: 0
    # fuse_type 表示使用的px4融合通道,0表示使用vision_pose通道，1表示使用odometry通道
    fuse_type: 1 # viobot输出odom格式的里程计，同时带有协方差，尝试使用odometry通道进行融合
    # params 表示需要查找确认的px4参数，命名与px4内部参数一致，类型为int/float两种，value表示值而非语义化(语义化参数会导致yaml难写和整个vision_pose节点产生很多的辅助函数用来分析字符串)
    params:
      - {name: EKF2_EV_CTRL, type: int, value: 15} # 首先确认EV_CTRL参数，从高到底分别是yaw,velocity,pos_z,pos_xy,这里置15 = 1111表示全融合
      - {name: EKF2_HGT_REF, type: int, value: 3} # 将高度参考设置为3 = vision
      - {name: EKF2_EV_DELAY, type: float, value: 30} # 请注意，float中几乎所有都是以ms作为单位
      - {name: EKF2_EV_NOISE_MD, type: int, value: 0} # 由于viobot输出的里程计中有动态的协方差，因此设置px4误差噪声取消息中的协方差

  MOCAP:
    source_id: 1
    fuse_type: 1 # 由于动捕系统没有协方差数据输入，其速度是使用pos对时间求导得出的，因此我们使用vision_pose进行融合，但是我这里想先尝试一下使用odometry
    params:
      - {name: EKF2_EV_CTRL, type: int, value: 15} # 首先确认EV_CTRL参数，从高到底分别是yaw,velocity,pos_z,pos_xy,这里置15 = 1111表示全融合
      - {name: EKF2_HGT_REF, type: int, value: 3} # 将高度参考设置为3 = vision
      - {name: EKF2_EV_DELAY, type: float, value: 0} # 请注意，float中几乎所有都是以ms作为单位

  VINS:
    source_id: 2
    params:
      - {name: EKF2_EV_CTRL, type: int, value: 15} # 首先确认EV_CTRL参数，从高到底分别是yaw,velocity,pos_z,pos_xy,这里置15 = 1111表示全融合
      - {name: EKF2_HGT_REF, type: int, value: 3} # 将高度参考设置为3 = vision
      - {name: EKF2_EV_DELAY, type: float, value: 30} # 请注意，float中几乎所有都是以ms作为单位
      - {name: EKF2_EV_NOISE_MD, type: int, value: 0} # 由于vins输出的里程计中有动态的协方差，因此设置px4误差噪声取消息中的协方差

  GAZEBO:
    source_id: 3
    params:
      - {name: EKF2_EV_CTRL, type: int, value: 15} # 首先确认EV_CTRL参数，从高到底分别是yaw,velocity,pos_z,pos_xy,这里置15 = 1111表示全融合
      - {name: EKF2_HGT_REF, type: int, value: 3} # 将高度参考设置为3 = vision
      - {name: EKF2_EV_DELAY, type: float, value: 30} # 请注意，float中几乎所有都是以ms作为单位
      - {name: EKF2_EV_NOISE_MD, type: int, value: 1} # 由于Gazebo输出里程计没有协方差，因此设置噪声为不依赖消息中的协方差
      - {name: EKF2_EVP_NOISE, type: float, value: 0.01} # 位置噪声，单位m(米)，由于Gazebo我们认为是绝对真值，因此噪声取最低为0.1
      - {name: EKF2_EVV_NOISE, type: float, value: 0.01} # 速度噪声，单位m/s(米每秒)
      - {name: EKF2_EVA_NOISE, type: float, value: 0.05} # 角度噪声，单位弧度(rad)
      
      