fixed_frame: "world"
status_timeout: 1.0
refresh_hz: 5.0

uav_name_prefix: "uav"
ugv_name_prefix: "ugv"

uav_swarm_cmd_topic: "/sunray/swarm/uav_swarm_cmd"
ugv_swarm_cmd_topic: "/sunray/swarm/ugv_swarm_cmd"
uav_swarm_state_topic: "/sunray/swarm/uav_swarm_state"
ugv_swarm_state_topic: "/sunray/swarm/ugv_swarm_state"
uav_swarm_rviz_topic: "/sunray/swarm/uav_rviz_markers"
ugv_swarm_rviz_topic: "/sunray/swarm/ugv_rviz_markers"

agents:
  uav:
    prefix: "uav"
    ids: [1,2]
  ugv:
    prefix: "ugv"
    ids: [1,2]
